# Site settings
title: Sam's Academic Blog
email: samuel_finlayson@hms.harvard.edu
description: "MD-PhD student working with Zak Kohane"
baseurl: ""
url: "http://sgfin.github.io"
twitter_username: samfin55
github_username: sgfin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
