# Site settings
title: Machine Learning and Medicine
email: samuel_finlayson@hms.harvard.edu
description: "By Sam Finlayson, MD-PhD student at Harvard-MIT"
baseurl: ""
url: "http://sgfin.github.io"
# twitter_username: IAmSamFin
github_username: sgfin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
